MaNguon/DoAnCoSo/Controllers/ChuDeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnCoSo.Models;

namespace DoAnCoSo.Controllers
{
    public class ChuDeController : Controller
    {
        // GET: ChuDe
        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        public ActionResult ChuDePartial()
        {
            return PartialView(db.ChuDes.Take(5).ToList());
        }
        public ViewResult SachTheoChuDe(int MaChuDe = 0)//biết đã trả về view
        {
            //Kiểm tra chủ đề tồn tại hay không
            ChuDe cd = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);//trả về 1 đối tượng phù hợp dk
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Truy xuất danh sách các quyển sách theo chủ đề
            List<Sach> lstSach = db.Saches.Where(n => n.MaChuDe == MaChuDe).OrderBy(n => n.GiaBan).ToList();
            if (lstSach.Count == 0)
            {
                ViewBag.Sach = "Không có sách nào thuộc chủ đề này";//truyền dữ liệu từ control đến view
            }
            //Gán danh sách chủ để
            ViewBag.lstChuDe = db.ChuDes.ToList();
            return View(lstSach);
        }
            //Hiển thị các chủ đề và sách theo chủ đề đầu tiên
            public ViewResult DanhMucChuDe()
            {
            //Lấy ra chủ đề đầu tiên trong csdl
            int MaChuDe = int.Parse(db.ChuDes.ToList().ElementAt(0).MaChuDe.ToString());
            //Tạo 1 viewbag gán sách theo chủ đề đầu tiên trong csdl
            ViewBag.SachTheoChuDe = db.Saches.Where(n => n.MaChuDe == MaChuDe).ToList();
            return View(db.ChuDes.ToList());
            }
    }
}

MaNguon/DoAnCoSo/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnCoSo.Models;

namespace DoAnCoSo.Controllers
{
    public class SachController : Controller
    {
        // GET: Sach

        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        public PartialViewResult SachMoiPartial()
        {
            var listSachMoi = db.Saches.Take(3).ToList();
            return PartialView(listSachMoi);
        }
        //Xem chi tiêt
        public  ViewResult XemChiTiet(int MaSach=0)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if(sach==null)
            {
                //trả về trang báo lỗi
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
    }
}

MaNguon/DoAnCoSo/Views/Layout/NguoiDungLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/NguoiDungCss/fonts.css" rel="stylesheet" />
    <link href="~/Content/NguoiDungCss/screen.css" rel="stylesheet" />
    @*chèn css của mình tự tạo**@
    <link href="~/Content/NguoiDungCss/NguoiDungCss.css" rel="stylesheet" />
    @*chèn Icon cho dep*@
    <link href="~/Content/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />



    <link href="~/NivoSlide/nivo-slider.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/NivoSlide/jquery.nivo.slider.js"></script>
    <script src="~/NivoSlide/jquery.nivo.slider.pack.js"></script>

</head>




<body>

    <div id="ToanTrang">
        <section class="blank">
            <div class="flash">
                <div class="DienThoai">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    1900-1081
                </div>
                <div class="DangKyDangNhap">
                    @Html.Action("GioHangPartial", "GioHang")
                    <i class="fa fa-sign-in"></i>
                    @Html.ActionLink("Đăng ký", "DangKy","NguoiDung",null, htmlAttributes: new { @class = "DangKy" })
                    <i class="fa fa-sign-out"></i>
                    @Html.ActionLink("Đăng nhập", "DangNhap","NguoiDung",null, htmlAttributes: new { @class = "DangNhap" })
                </div>


            </div>

            <div class="flash success" id="divDanhMuc">
                <div id="txtfind">
                    @using (Html.BeginForm())
                    {
                
                        @Html.TextBox("txttimkiem", "", htmlAttributes: new { @class = "textboxTimKiem", @placeholder = "Nhập từ khóa cần tìm.... " })
                    }
                </div>
                <ul class="Menu">
                    <li><a href="/Home">Trang Chủ</a>  </li>
                    <li><a href="/Home#divRight">Giới Thiệu</a></li>
                    <li><a href="#">Liên Hệ</a></li>
                    <li><a href="#">Hướng Dẫn</a></li>
                    <li><a href="ChuDe/DanhMucChuDe#NoiDung">Sách</a></li>
                </ul>
            </div>
        </section>


        <section>
            <div id="MenuTrai">
                @*chèn vào partial view sách mới*@
                <div class="activity">
                    @Html.Action("SachMoiPartial", "Sach")
                   
                </div>
            </div>
            <div id="slider" class="nivoSlider">
                <img src="~/HinhAnh/IMG_7935.jpg" />
                <img src="~/HinhAnh/images (1).jpg" />
                <img src="~/HinhAnh/images.png" />
                <img src="~/HinhAnh/images.jpg" />
            </div>
            <div style="clear:both"></div>
        </section>
        <div id="NoiDung">
            @RenderBody()
        </div>
        <div id="divChuDeVaNXB">
            <section>

                <div>
                    @Html.Action("ChuDePartial","ChuDe")
                </div>


            </section>

            @*Nhà xuất bản*@
            <section class="blank items">
                <div id="divLeft">
                    <div class="item">
                        <div class="item-info">
                            <h1>Nhà Xuất Bản</h1>
                            <div>
                                   @Html.Action("NXBPartial","NhaXuatBan")
                            
                            </div>
                            <img src="http://lorempixel.com/400/300/" alt="Image">
                        </div>
                    </div>
                 </div>
                    <div id="divRight">
                        @RenderSection("NoiDUngBenPhai",false)
                    </div>

            </section>
        </div>
        <div style="clear:both"></div>
    <div>
        <a href="#" class="button button-buy">Chào Mừng Bạn Đến Với Tủ Sách Waka</a>
    </div>

    </div>

        <script type="text/javascript">
$(window).load(function () { $('#slider').nivoSlider({controlNav:false}); });
        </script>
</body>

</html>